### ISSUE TITLE
iPad should have a default zoom of 80%

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etflex#124]
We need to make the following dependent on 'media' type

``` CSS
body {
  zoom: 80%;
}
```
