### ISSUE TITLE
Clean up help texts

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etflex#147]
Let's make them uniform, preferrable in Markdown.

such as:

```
car: |-
### Some header text

Lorem Ipsum paragraph
```

in stead of the separate header and body thing we have now.

We could also see if the state of the element is present in the translation file, if it is, then we go there:

```
car:
  eco:
### Some header text

Lorem Ipsum paragraph

  suv:
### Some header text

Lorem Ipsum paragraph

```

Then we can get rid of the logic in e.g. car.coffee, stating what is the header and boy text.
